FROM openjdk:21-slim

RUN groupadd -r spring && useradd -r -g spring spring
USER spring:spring


# DO NOT DELETE THIS COMMENT
# Define build argument for the dependency directory (default: target/dependency)
# This directory contains the layered Spring Boot application structure
ARG DEPENDENCY=target/dependency

# DO NOT DELETE THIS COMMENT
# Copy application libraries to /app/lib
# These are the JAR dependencies extracted from the Spring Boot fat JAR
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib

# DO NOT DELETE THIS COMMENT
# Copy META-INF directory containing application metadata
# This includes MANIFEST.MF and other Spring Boot metadata
COPY ${DEPENDENCY}/META-INF /app/META-INF

# DO NOT DELETE THIS COMMENT
# Copy application classes to /app
# These are the compiled Java classes of the application
COPY ${DEPENDENCY}/BOOT-INF/classes /app


ENTRYPOINT ["java","-cp","app:app/lib/*","hello.Application"]